### ISSUE TITLE
Broken example

### ISSUE THREAD

**Issue by Gargo** [michaelhenry/RxRetroSwift#1]
pod install
Analyzing dependencies
Fetching podspec for `RxRetroSwift` from `../`
[!] The `RxRetroSwift` pod failed to validate due to 1 error:
    - ERROR | version: A version is required.

**Comment by michaelhenry** [comment]
@Gargo please execute this using command line.
```
export RXRETROFIT_VERSION=1.0 
```

because submission to cocoapods is done automatically using git tag. 
Thank you

**Comment by michaelhenry** [comment]
I will add a default .env file so that no need to do it manually during development. thanks

**Comment by michaelhenry** [comment]
@Gargo please pull the latest master branch thanks
