### ISSUE TITLE
Feature request - multiple base url support

### ISSUE THREAD

**Issue by Gargo** [michaelhenry/RxRetroSwift#26]

**Comment by michaelhenry** [comment]
@Gargo actually you can create your own method the return a request with the base url that you want.
RequestCaller accepts any URLRequest. You can also specify the base url inside RequestModel. so this 's already supported. 

https://github.com/michaelhenry/RxRetroSwift/blob/6a9bf25cc34b29a44b4fde3e1335d11eef1d3b9e/Sources/RxRetroSwift/Models/RequestModel.swift#L36
