### ISSUE TITLE
Add the file sending option

### ISSUE THREAD

**Issue by amitvasundhara** [michaelhenry/RxRetroSwift#27]
As per my developing i need to send image to server but no multipart/formdata option given in library.

**Comment by michaelhenry** [comment]
@amitvasundhara Sorry, I haven't included that yet in the library but you can this wrapper https://gist.github.com/michaelhenry/4e34ed2a5ec650a64008505b0837814f 

and to use this wrapper with `RxRetroswift`

```swift
 guard let pngData = UIImagePNGRepresentation(image) else { fatalError() }
  var profileImageRequest = MultipartData(
      data: pngData,
      key: "image",
      filename: "profile_image.png",
      mimeType: "image/png")
      .asURLRequest(url: URL(string: "http://your_target_url")!)!
    return caller.call(profileImageRequest)
```

**Comment by amitvasundhara** [comment]
Thanks man, your creation was awesome 👍

**Comment by michaelhenry** [comment]
@amitvasundhara thank you
