### ISSUE TITLE
#405 error when call without domain name like (http://123.123.123.123).

### ISSUE THREAD

**Issue by amitvasundhara** [michaelhenry/RxRetroSwift#28]
When I call an API without domainName for ex. (http://123.123.123.123),  It's responding with wrong response code (#404 or #405). Otherwise working well. I've also provided app transport security(Arbitrary loads = true).

**Comment by michaelhenry** [comment]
@amitvasundhara can you `ping` that `IP` to check that IP exist or not. 

In my end it just timed-out which is the expected one. 

btw,

`404` means `page not found` and `405` means `method not allowed`, so I guess the IP you're hitting a valid server. Please confirm if you can ping the IP you're trying to access. thanks

**Comment by amitvasundhara** [comment]
Please Check This Postman Collection It's working : https://www.getpostman.com/collections/ed0c0c7d4405e42b578b

**Comment by michaelhenry** [comment]
@amitvasundhara oh I see, there is a chance that you're sending a `GET` request from `RxRetroSwift` instead of `POST`.

**Comment by amitvasundhara** [comment]
No, I'm sending POST request.

**Comment by michaelhenry** [comment]
@amitvasundhara would it be possible to see a snippet of your code? thanks

**Comment by amitvasundhara** [comment]
Solved This issue by just using BaseURL and path method actually i'm using whole URL in base URL so as per requestModel you're appending path in baseURL with "/" so That's the issue
Thanks.
